name: Build Release Sample

on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/release-[0-9]+.[0-9].[0-9]'
      - 'main'

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sample Output
        run: echo "It Ran"