name: Check Dependency Versions Workflow

on:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  scheduled_dependencies_check_job:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Check Dependency Versions
        run: ./gradlew dependencyUpdates