name: Test

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.asciidoc'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

jobs:
  job1:
    name: Testing
    runs-on: ubuntu-latest
    steps:

      - run: 'echo "working"'