name: Triggered Dependencies And Test Workflow

on:
  push:
  repository_dispatch:

jobs:
  triggered_dependencies_tests_job:
    name: Check Dependencies & Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Log Inputs
        run: |
          echo "dependencies: ${{ github.event.client_payload.dependencies }}"
          echo "tests: ${{ github.event.client_payload.tests }}"

      - name: Check Dependency Versions
        if: github.event.client_payload.dependencies == true
        run: ./gradlew dependencyUpdates

      - name: Run Tests
        if: github.event.client_payload.tests == true
        run: ./gradlew test