name: Triggered Dependencies And Test Workflow

on:
  repository_dispatch:

jobs:
  triggered_dependencies_tests_job:
    name: Check Dependencies & Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Check Dependency Versions
        if: github.event.client_payload.dependencies == true
        run: ./gradlew dependencyUpdates

      - name: Run Tests
        if: github.event.client_payload.tests == true
        run: ./gradlew test